### PR TITLE
Add rails route to activity library

### LINKED ISSUE #38: As a user I want to see the Activity Library
- [ ] In ember we need a rails route to the Activity Library.

### PR DESCRIPTION
**Pull request by zulaica**
Fixes #38
Compares to #44

### CODE REVIEW

**Comment by zulaica** [comment]
This should be checked/merged into #44 first.

**Comment by smashedlife** [comment]
I am getting the following build error:

```
File: /Users/jso/Development/revelation/ember-admin/node_modules/ember-cli-revelation-ui/bower_components/bootstrap/scss/_card.scss (8)
Undefined variable: "$card-bg".
Error: Undefined variable: "$card-bg".
    at options.error (/Users/jso/Development/revelation/ember-admin/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:276:32)
```

**Comment by zulaica** [comment]
This might be tied to the add-on needing to be built independently. https://github.com/revelation/ember-cli-revelation-ui/issues/66

Try pulling the add-on and running bower install/npm install.

**Comment by kscherling** [comment]
They updated the bootstrap v4-dev branch so our varaibles file needs to be fixed...

**Pull request merged**
