### PR TITLE
Install RUI Addon Library

### PR DESCRIPTION
**Pull request by smashedlife**

### CODE REVIEW

**Comment by smashedlife** [comment]
@zulaica CORS for the fonts from the ember addon are not set up correctly. Since we proxy over from the ember server, it currently is being blocked.

emberadmin

**Comment by zulaica** [comment]
I'm guessing that's the Google font. The easiest fix would be to add that manually to the project, but I wonder if a better solution might be the answer. 

I'll add the fix for now and then set up an issue in the RUI repo.

**Comment by zulaica** [comment]
Sorry, just noticed the screenshot. The FontAwesome icon isn't loading. This is more a project-related issue since we're proxying. I'll add the fix. I don't think this qualifies as an issue with the addon.

**Comment by zulaica** [comment]
CORS issue should be sorted now.

**Comment by kscherling** [comment]
@zulaica is this good to go?

**Comment by zulaica** [comment]
Yeah, this should be all set.

**Comment by zulaica** [comment]
... let me make sure this is up-to-date with master first.

**Comment by zulaica** [comment]
Okay, yeah, this PR is good to go.

**Pull request merged**
